name: CI Testing

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Instal libc++
        run: |
          sudo apt-get install libc++

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch latest XLSynth release
        id: fetch-xlsynth
        run: |
          API_URL="https://api.github.com/repos/xlsynth/xlsynth/releases/latest"
          RESPONSE=$(curl -s $API_URL)
          DSLX_INTERPRETER_BINARY_URL=$(echo $RESPONSE | jq -r '.assets[] | select(.name == "dslx_interpreter_main-ubuntu2204") | .browser_download_url')
          DSLX_TYPECHECK_BINARY_URL=$(echo $RESPONSE | jq -r '.assets[] | select(.name == "typecheck_main-ubuntu2204") | .browser_download_url')
          DSLX_STDLIB_URL=$(echo $RESPONSE | jq -r '.assets[] | select(.name == "dslx_stdlib.tar.gz") | .browser_download_url')
          if [ -z "$DSLX_INTERPRETER_BINARY_URL" ] || [ -z "$DSLX_TYPECHECK_BINARY_URL" ] || [ -z "$DSLX_STDLIB_URL" ]; then
            echo "Error: Could not find required assets in the latest release." >&2
            exit 1
          fi
          echo "DSLX_INTERPRETER_BINARY_URL=$DSLX_INTERPRETER_BINARY_URL" >> $GITHUB_ENV
          echo "DSLX_TYPECHECK_BINARY_URL=$DSLX_TYPECHECK_BINARY_URL" >> $GITHUB_ENV
          echo "DSLX_STDLIB_URL=$DSLX_STDLIB_URL" >> $GITHUB_ENV

      - name: Download DSLX interpreter binary
        run: |
          curl -L "$DSLX_INTERPRETER_BINARY_URL" -o dslx_interpreter_main
          chmod +x dslx_interpreter_main
          export PATH="$PWD:$PATH"
          echo "PATH=$PWD:$PATH" >> $GITHUB_ENV

      - name: Download DSLX typecheck binary
        run: |
          curl -L "$DSLX_TYPECHECK_BINARY_URL" -o typecheck_main
          chmod +x typecheck_main

      - name: Download and extract DSLX standard library
        run: |
          curl -L "$DSLX_STDLIB_URL" -o dslx_stdlib.tar.gz
          tar -xzf dslx_stdlib.tar.gz
          export DSLX_STDLIB_PATH=$PWD/xls/dslx/stdlib
          echo "DSLX_STDLIB_PATH=$PWD/xls/dslx/stdlib" >> $GITHUB_ENV

      - name: Run pre-commit hooks
        env:
          DSLX_STDLIB_PATH: ${{ env.DSLX_STDLIB_PATH }}
        run: |
          pre-commit install
          SKIP=no-commit-to-branch pre-commit run --all-files

      - name: Run pytest  # Avoid relying on the pre-commit hook stage.
        run: |
          pytest test_prompt.py
